import { copyFile, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { randomBytes } from 'node:crypto';

const GAME_MODE = '[/Script/ShooterGame.ShooterGameMode]';
const SERVER = '[ServerSettings]';
const LEVELS = '[CustomLevelDistrib]';
const CYBERS = '[CybersStructures]';
const definition = (key,label,min,max,help,file='gus',section=file==='game'?GAME_MODE:SERVER) => ({key,label,min,max,help,file,section});

export const rateDefinitions = Object.freeze([
  definition('XPMultiplier','Experience',0.1,100,'Higher gives players and tames more XP.'), definition('HarvestAmountMultiplier','Harvest amount',0.1,100,'Higher gives more resources per hit.'),
  definition('TamingSpeedMultiplier','Taming speed',0.1,100,'Higher makes active and knockout taming faster.'), definition('PassiveTameIntervalMultiplier','Passive feed interval',0.05,10,'Lower shortens the wait between passive feeds.'),
  definition('PlayerResistanceMultiplier','Damage players receive',0.1,5,'Lower reduces incoming damage.'), definition('ResourcesRespawnPeriodMultiplier','Resource respawn',0.1,10,'Lower respawns resources sooner.'),
  definition('PlayerCharacterFoodDrainMultiplier','Food drain',0.1,10,'Lower means hunger drains more slowly.'), definition('PlayerCharacterWaterDrainMultiplier','Water drain',0.1,10,'Lower means thirst drains more slowly.'),
  definition('MatingIntervalMultiplier','Mating cooldown',0.01,10,'Lower lets creatures mate again sooner.','game'), definition('MatingSpeedMultiplier','Mating progress',0.1,100,'Higher fills the mating bar faster.','game'),
  definition('EggHatchSpeedMultiplier','Egg hatch speed',0.1,100,'Higher makes fertilized eggs hatch faster.','game'), definition('BabyMatureSpeedMultiplier','Baby maturation',0.1,100,'Higher makes babies mature faster.','game'),
  definition('BabyCuddleIntervalMultiplier','Imprint interval',0.01,10,'Lower requests imprint care sooner.','game'), definition('BabyImprintAmountMultiplier','Imprint per care',0.1,100,'Higher gives more imprint progress per care.','game'),
  definition('CropGrowthSpeedMultiplier','Crop growth',0.1,100,'Higher makes crops grow faster.','game'), definition('StructureResistanceMultiplier','Structure toughness',0.05,5,'Lower makes structures take less damage.'),
  definition('DinoCharacterFoodDrainMultiplier','Dino food drain',0.1,10,'Lower means dinos get hungry more slowly.'), definition('DinoCharacterStaminaDrainMultiplier','Dino stamina drain',0.1,10,'Lower means dinos tire more slowly.'),
]);

export const progressionDefinitions = Object.freeze([
  definition('KillXPMultiplier','Kill XP',0.1,20,'Stacks with the main XP rate.','game'), definition('PerLevelStatsMultiplier_Player[1]','Player stamina / level',0.1,20,'Stamina gained per player level point.','game'),
  definition('PerLevelStatsMultiplier_Player[7]','Player weight / level',0.1,20,'Weight gained per player level point.','game'), definition('PerLevelStatsMultiplier_Player[8]','Player melee / level',0.1,20,'Melee gained per player level point.','game'),
  definition('PerLevelStatsMultiplier_Player[11]','Player crafting / level',0.1,20,'Crafting skill gained per point.','game'), definition('PerLevelStatsMultiplier_Player[9]','Player movement / level',0.1,20,'Native ASA speed leveling has no hard cap.','game'),
  definition('PerLevelStatsMultiplier_Player[10]','Player fortitude / level',0.1,20,'Improves heat, cold and knockout resistance.','game'), definition('PerLevelStatsMultiplier_DinoTamed[0]','Dino health / level',0.1,10,'Health gained per tamed dino level.','game'),
  definition('PerLevelStatsMultiplier_DinoTamed[1]','Dino stamina / level',0.1,10,'Stamina gained per tamed dino level.','game'), definition('PerLevelStatsMultiplier_DinoTamed[7]','Dino weight / level',0.1,20,'Weight gained per tamed dino level.','game'),
  definition('PerLevelStatsMultiplier_DinoTamed[8]','Dino melee / level',0.1,10,'Melee gained per tamed dino level.','game'), definition('DayCycleSpeedScale','Whole day cycle',0.1,10,'Higher makes the whole cycle pass faster.'),
  definition('DayTimeSpeedScale','Daytime speed',0.1,10,'Lower makes daylight last longer.'), definition('NightTimeSpeedScale','Night speed',0.1,10,'Higher makes nighttime end sooner.'),
]);

export const wildDefinitions = Object.freeze([
  definition('OverrideOfficialDifficulty','Difficulty / max level',0.2,5,'Value × 30 is the approximate max wild level.'), definition('DinoCountMultiplier','Dino population',0.1,5,'Overall wild dino population.'),
  definition('DinoCharacterHealthRecoveryMultiplier','Dino health regeneration',0.1,20,'Affects wild and tamed dinos.'), definition('SupplyCrateLootQualityMultiplier','Supply crate quality',0.5,10,'Higher improves supply-crate loot quality.'),
  definition('PerLevelStatsMultiplier_DinoWild[0]','Wild dino health / level',0.1,3,'Lower makes high-level wild dinos less tanky.','game'), definition('PerLevelStatsMultiplier_DinoWild[8]','Wild dino melee / level',0.1,3,'Lower makes high-level wild dinos hit less hard.','game'),
]);

export const fileHelp = Object.freeze([
  {name:'Launch settings',relative:'server-config.cmd',detail:'Server name, map, player limit, LAN IP, ports, active mods, and native speed-leveling flag.',safety:'Advanced: malformed startup values can prevent launch.'},
  {name:'General rates',relative:'server/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini',detail:'Rates, passwords, world rules, day/night timing, and mod sections.',safety:'Most changes require a restart.'},
  {name:'Progression + breeding',relative:'server/ShooterGame/Saved/Config/WindowsServer/Game.ini',detail:'Player/dino level gains, breeding, imprinting, XP categories, and recipes.',safety:'Duplicate or malformed lines may be ignored by ASA.'},
  {name:'Permanent admins',relative:'server/ShooterGame/Saved/AllowedCheaterAccountIDs.txt',detail:'One 32-character EOS/OSS Account ID per line. PSN names do not work.',safety:'Do not share account IDs publicly.'},
  {name:'World + character saves',relative:'server/ShooterGame/Saved/SavedArks',detail:'World, player, tribe, and map progress.',safety:'Never edit or delete while ASA is running.'},
  {name:'Server logs',relative:'server/ShooterGame/Saved/Logs',detail:'Startup, mod-loading, connection, crash, and runtime messages.',safety:'Read-only troubleshooting.'},
  {name:'Backups',relative:'backups',detail:'Timestamped recovery copies created by safe backup and config saves.',safety:'Restore only while ASA is stopped.'},
]);

const clean=(text)=>text.replace(/^\uFEFF/,''); const numberText=(value)=>Number(value).toFixed(4).replace(/0+$/,'').replace(/\.$/,'');
const paths=(root)=>({gus:join(root,'server','ShooterGame','Saved','Config','WindowsServer','GameUserSettings.ini'),game:join(root,'server','ShooterGame','Saved','Config','WindowsServer','Game.ini'),cmd:join(root,'server-config.cmd'),admins:join(root,'server','ShooterGame','Saved','AllowedCheaterAccountIDs.txt')});
function iniRaw(text,section,key,fallback=''){let active=false;for(const raw of clean(text).split(/\r?\n/)){const line=raw.trim();if(/^\[.*\]$/.test(line))active=line.toLowerCase()===section.toLowerCase();else if(active&&line.toLowerCase().startsWith(`${key.toLowerCase()}=`))return line.slice(line.indexOf('=')+1).trim();}return fallback;}
function iniNumber(text,section,key,fallback=1){const raw=iniRaw(text,section,key,'');if(raw==='')return fallback;const value=Number(raw);return Number.isFinite(value)?value:fallback;} function iniBool(text,section,key,fallback=false){return iniRaw(text,section,key,String(fallback)).toLowerCase()==='true';}
function setIniRaw(text,section,key,value){const lines=clean(text).split(/\r?\n/);let sectionIndex=lines.findIndex((line)=>line.trim().toLowerCase()===section.toLowerCase());if(sectionIndex<0){if(lines.at(-1)?.trim())lines.push('');lines.push(section);sectionIndex=lines.length-1;}let end=lines.length;for(let i=sectionIndex+1;i<lines.length;i++)if(/^\s*\[.*\]\s*$/.test(lines[i])){end=i;break;}const offset=lines.slice(sectionIndex+1,end).findIndex((line)=>line.trim().toLowerCase().startsWith(`${key.toLowerCase()}=`));const next=`${key}=${value}`;if(offset>=0)lines[sectionIndex+1+offset]=next;else lines.splice(end,0,next);return lines.join('\r\n');}
const setDefinition=(text,item,value)=>setIniRaw(text,item.section,item.key,numberText(value)); async function atomicWrite(path,content){const temp=`${path}.web-${randomBytes(5).toString('hex')}.tmp`;await writeFile(temp,content,'utf8');await rename(temp,path);} const readOptional=async(path)=>{try{return await readFile(path,'utf8');}catch{return '';}}; const numericGroup=(defs,gus,game)=>Object.fromEntries(defs.map((item)=>[item.key,iniNumber(item.file==='game'?game:gus,item.section,item.key,1)]));

export async function loadManagerConfig(projectRoot){const path=paths(projectRoot);const[gus,game,cmd,adminText]=await Promise.all([readFile(path.gus,'utf8'),readFile(path.game,'utf8'),readFile(path.cmd,'utf8'),readOptional(path.admins)]);const mods=(clean(cmd).match(/^set\s+"MODS=([^"]*)"/im)?.[1]||'').split(',').map((id)=>id.trim()).filter(Boolean);const speed=(clean(cmd).match(/^set\s+"ALLOW_SPEED_LEVELING=([^"]*)"/im)?.[1]||'False').toLowerCase()==='true';const high=iniBool(gus,LEVELS,'WantsHighLevels'),rag=iniBool(gus,LEVELS,'WantsRagLevels');return{rates:numericGroup(rateDefinitions,gus,game),rateDefinitions,mods,progression:numericGroup(progressionDefinitions,gus,game),progressionDefinitions,allowSpeedLeveling:speed,wild:numericGroup(wildDefinitions,gus,game),wildDefinitions,levelDistribution:high?'high':rag?'rag':'equal',important:{serverPVE:iniBool(gus,SERVER,'ServerPVE'),allowFlyerCarryPvE:iniBool(gus,SERVER,'AllowFlyerCarryPvE'),alwaysAllowStructurePickup:iniBool(gus,SERVER,'AlwaysAllowStructurePickup',true),autosaveMinutes:iniNumber(gus,SERVER,'AutoSavePeriodMinutes',15),maxTamedDinos:iniNumber(gus,SERVER,'MaxTamedDinos',2500),noRespawnPenalty:!iniBool(game,GAME_MODE,'bIncreasePvPRespawnInterval',true),simpleBedCooldown:iniNumber(gus,CYBERS,'SimpleBedCooldown',30),modernBedCooldown:iniNumber(gus,CYBERS,'ModernBedCooldown',12),joinPasswordConfigured:Boolean(iniRaw(gus,SERVER,'ServerPassword','')),adminPasswordConfigured:Boolean(iniRaw(gus,SERVER,'ServerAdminPassword',''))},admins:clean(adminText).split(/\r?\n/).map((id)=>id.trim()).filter(Boolean),files:fileHelp.map((item)=>({...item,path:join(projectRoot,item.relative)}))};}
function validateNumbers(input,defs){const output={};for(const item of defs){const value=Number(input?.[item.key]);if(!Number.isFinite(value)||value<item.min||value>item.max)throw new Error(`${item.label} must be between ${item.min} and ${item.max}.`);output[item.key]=value;}return output;}
function validatePassword(change,label,allowClear){const mode=change?.mode||'keep';if(!['keep','replace',...(allowClear?['clear']:[])].includes(mode))throw new Error(`${label} action is invalid.`);const value=String(change?.value||'');if(mode==='replace'&&!/^[A-Za-z0-9_-]{4,64}$/.test(value))throw new Error(`${label} must use 4-64 letters, numbers, underscores, or hyphens.`);return{mode,value:mode==='replace'?value:''};}
export function validateManagerConfig(input){if(!input||typeof input!=='object')throw new Error('Configuration payload is missing.');const mods=Array.isArray(input.mods)?input.mods.map((id)=>String(id).trim()):[];if(mods.length>100||mods.some((id)=>!/^\d+$/.test(id))||new Set(mods).size!==mods.length)throw new Error('Mods must be unique numeric CurseForge project IDs.');if(typeof input.allowSpeedLeveling!=='boolean')throw new Error('Movement-speed leveling must be true or false.');if(!['equal','high','rag'].includes(input.levelDistribution))throw new Error('Wild dino level distribution is invalid.');const important=input.important||{};for(const key of ['serverPVE','allowFlyerCarryPvE','alwaysAllowStructurePickup','noRespawnPenalty'])if(typeof important[key]!=='boolean')throw new Error(`${key} must be true or false.`);const cleanImportant={};for(const[key,min,max]of[['autosaveMinutes',5,60],['maxTamedDinos',100,5000],['simpleBedCooldown',0,600],['modernBedCooldown',0,600]]){const value=Number(important[key]);if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${key} must be a whole number from ${min} to ${max}.`);cleanImportant[key]=value;}const admins=Array.isArray(input.admins)?input.admins.map((id)=>String(id).trim()):[];if(admins.length>100||admins.some((id)=>!/^[A-Za-z0-9]{32}$/.test(id))||new Set(admins).size!==admins.length)throw new Error('Admins must be unique 32-character EOS/OSS Account IDs.');return{rates:validateNumbers(input.rates,rateDefinitions),mods,progression:validateNumbers(input.progression,progressionDefinitions),allowSpeedLeveling:input.allowSpeedLeveling,wild:validateNumbers(input.wild,wildDefinitions),levelDistribution:input.levelDistribution,important:{...cleanImportant,serverPVE:important.serverPVE,allowFlyerCarryPvE:important.allowFlyerCarryPvE,alwaysAllowStructurePickup:important.alwaysAllowStructurePickup,noRespawnPenalty:important.noRespawnPenalty,joinPassword:validatePassword(important.joinPassword,'Join password',true),adminPassword:validatePassword(important.adminPassword,'Admin password',false)},admins};}
export async function applyManagerConfig(projectRoot,validated){const path=paths(projectRoot),stamp=new Date().toISOString().replace(/[:.]/g,'-'),snapshot=join(projectRoot,'backups','ConfigHistory',`web-manager-${stamp}`);await mkdir(snapshot,{recursive:true});await Promise.all([path.gus,path.game,path.cmd].map((source)=>copyFile(source,join(snapshot,basename(source)))));try{await copyFile(path.admins,join(snapshot,basename(path.admins)));}catch{}let[gus,game,cmd]=await Promise.all([readFile(path.gus,'utf8'),readFile(path.game,'utf8'),readFile(path.cmd,'utf8')]);for(const[defs,values]of[[rateDefinitions,validated.rates],[progressionDefinitions,validated.progression],[wildDefinitions,validated.wild]])for(const item of defs){if(item.file==='game')game=setDefinition(game,item,values[item.key]);else gus=setDefinition(gus,item,values[item.key]);}gus=setIniRaw(gus,LEVELS,'WantsEqualLevels',String(validated.levelDistribution==='equal'));gus=setIniRaw(gus,LEVELS,'WantsHighLevels',String(validated.levelDistribution==='high'));gus=setIniRaw(gus,LEVELS,'WantsRagLevels',String(validated.levelDistribution==='rag'));const imp=validated.important;gus=setIniRaw(gus,SERVER,'ServerPVE',String(imp.serverPVE));gus=setIniRaw(gus,SERVER,'AllowFlyerCarryPvE',String(imp.allowFlyerCarryPvE));gus=setIniRaw(gus,SERVER,'AlwaysAllowStructurePickup',String(imp.alwaysAllowStructurePickup));gus=setIniRaw(gus,SERVER,'AutoSavePeriodMinutes',String(imp.autosaveMinutes));gus=setIniRaw(gus,SERVER,'MaxTamedDinos',String(imp.maxTamedDinos));gus=setIniRaw(gus,CYBERS,'SimpleBedCooldown',String(imp.simpleBedCooldown));gus=setIniRaw(gus,CYBERS,'ModernBedCooldown',String(imp.modernBedCooldown));game=setIniRaw(game,GAME_MODE,'bIncreasePvPRespawnInterval',String(!imp.noRespawnPenalty));if(imp.joinPassword.mode==='replace')gus=setIniRaw(gus,SERVER,'ServerPassword',imp.joinPassword.value);else if(imp.joinPassword.mode==='clear')gus=setIniRaw(gus,SERVER,'ServerPassword','');if(imp.adminPassword.mode==='replace')gus=setIniRaw(gus,SERVER,'ServerAdminPassword',imp.adminPassword.value);const replaceCmd=(text,key,value)=>{const regex=new RegExp(`^set\\s+"${key}=[^"]*"`,'im');if(!regex.test(text))throw new Error(`Missing ${key} in server-config.cmd.`);return clean(text).replace(regex,`set "${key}=${value}"`);};cmd=replaceCmd(cmd,'MODS',validated.mods.join(','));cmd=replaceCmd(cmd,'ALLOW_SPEED_LEVELING',String(validated.allowSpeedLeveling));await atomicWrite(path.gus,gus);await atomicWrite(path.game,game);await atomicWrite(path.cmd,cmd);await mkdir(join(projectRoot,'server','ShooterGame','Saved'),{recursive:true});await atomicWrite(path.admins,validated.admins.length?`${validated.admins.join('\r\n')}\r\n`:'');return{snapshot,restartRequired:true};}
