'use client';
import { useEffect, useMemo, useState } from 'react';

type StatusPayload={timestamp:string;server:{running:boolean;pid:number|null;privateMemoryGb:number;name:string;map:string;mapId:string;maxPlayers:number|null;modCount:number};host:{cpuPercent:number;memoryPercent:number;memoryUsedGb:number;memoryTotalGb:number;diskFreeGb:number};backup:{found:boolean;timestamp:string|null;name:string|null}};
type ActionId='start'|'stop'|'restart'|'backup'|'update'|'save'|'dinowipe'; type ActionJob={action?:ActionId;label?:string;state:'idle'|'running'|'success'|'failed';message?:string};
type NumberDefinition={key:string;label:string;min:number;max:number;help:string}; type Important={serverPVE:boolean;allowFlyerCarryPvE:boolean;alwaysAllowStructurePickup:boolean;autosaveMinutes:number;maxTamedDinos:number;noRespawnPenalty:boolean;simpleBedCooldown:number;modernBedCooldown:number;joinPasswordConfigured:boolean;adminPasswordConfigured:boolean};
type ManagerConfig={rates:Record<string,number>;rateDefinitions:NumberDefinition[];mods:string[];progression:Record<string,number>;progressionDefinitions:NumberDefinition[];allowSpeedLeveling:boolean;wild:Record<string,number>;wildDefinitions:NumberDefinition[];levelDistribution:'equal'|'high'|'rag';important:Important;admins:string[];files:{name:string;path:string;detail:string;safety:string}[]};
type Draft={rates:Record<string,number>;mods:string[];progression:Record<string,number>;allowSpeedLeveling:boolean;wild:Record<string,number>;levelDistribution:'equal'|'high'|'rag';important:Omit<Important,'joinPasswordConfigured'|'adminPasswordConfigured'>&{joinPassword:{mode:'keep'|'replace'|'clear';value:string};adminPassword:{mode:'keep'|'replace';value:string}};admins:string[]};
type ConfigPreview={token:string;changes:{group:string;key:string;from:string|number|boolean;to:string|number|boolean}[]};
const actions:{id:ActionId;icon:string;label:string;detail:string;warning:string}[]=[
  {id:'start',icon:'▶',label:'Start server',detail:'Original startup script',warning:'Start the ASA server now?'},{id:'stop',icon:'■',label:'Safe stop',detail:'Save + graceful shutdown',warning:'Safely save and stop the server? Everyone online will disconnect.'},{id:'restart',icon:'↻',label:'Restart',detail:'Player warning first',warning:'Warn players, save, stop, and restart?'},{id:'backup',icon:'⬡',label:'Backup + restart',detail:'Verified save snapshot',warning:'Warn players, save, back up, and restart?'},{id:'update',icon:'⇧',label:'Update + restart',detail:'ASA App 2430930',warning:'Update and validate ASA, then restart?'},{id:'save',icon:'✓',label:'Save world',detail:'Local RCON',warning:'Save the current world immediately?'},{id:'dinowipe',icon:'◇',label:'Reset wild dinos',detail:'Tames stay safe',warning:'Destroy and respawn all wild dinos? Tames are untouched.'},
];

function NumberGrid({definitions,values,onChange}:{definitions:NumberDefinition[];values:Record<string,number>;onChange:(key:string,value:number)=>void}){return <div className="ratesGrid">{definitions.map((item)=><label className="rateField" key={item.key}><span><b>{item.label}</b><small>{item.help}</small></span><input type="number" min={item.min} max={item.max} step="0.01" value={values[item.key]??1} onChange={(event)=>onChange(item.key,Number(event.target.value))}/><em>{item.min}–{item.max}</em></label>)}</div>}
const draftFrom=(config:ManagerConfig):Draft=>({rates:{...config.rates},mods:[...config.mods],progression:{...config.progression},allowSpeedLeveling:config.allowSpeedLeveling,wild:{...config.wild},levelDistribution:config.levelDistribution,important:{serverPVE:config.important.serverPVE,allowFlyerCarryPvE:config.important.allowFlyerCarryPvE,alwaysAllowStructurePickup:config.important.alwaysAllowStructurePickup,autosaveMinutes:config.important.autosaveMinutes,maxTamedDinos:config.important.maxTamedDinos,noRespawnPenalty:config.important.noRespawnPenalty,simpleBedCooldown:config.important.simpleBedCooldown,modernBedCooldown:config.important.modernBedCooldown,joinPassword:{mode:'keep',value:''},adminPassword:{mode:'keep',value:''}},admins:[...config.admins]});

export default function Home(){
  const[status,setStatus]=useState<StatusPayload|null>(null),[error,setError]=useState(''),[job,setJob]=useState<ActionJob>({state:'idle'}),[confirming,setConfirming]=useState<ActionId|null>(null),[actionError,setActionError]=useState('');
  const[config,setConfig]=useState<ManagerConfig|null>(null),[draft,setDraft]=useState<Draft|null>(null),[newMod,setNewMod]=useState(''),[newAdmin,setNewAdmin]=useState(''),[configMessage,setConfigMessage]=useState(''),[preview,setPreview]=useState<ConfigPreview|null>(null);
  useEffect(()=>{let active=true;const load=async()=>{try{const response=await fetch('/api/status',{cache:'no-store',credentials:'include'});if(!response.ok)throw new Error();const data=await response.json() as StatusPayload;if(active){setStatus(data);setError('');}}catch{if(active)setError('Local status service is offline');}};load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};},[]);
  const loadConfig=async()=>{try{const response=await fetch('/api/config',{cache:'no-store',credentials:'include'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json() as ManagerConfig;setConfig(data);setDraft(draftFrom(data));}catch{setConfigMessage('Could not load manager settings.');}};
  useEffect(()=>{const timer=setTimeout(loadConfig,0);return()=>clearTimeout(timer);},[]);
  useEffect(()=>{let active=true;const load=async()=>{try{const response=await fetch('/api/actions',{cache:'no-store',credentials:'include'});if(response.ok&&active)setJob(await response.json() as ActionJob);}catch{}};load();const timer=setInterval(load,1500);return()=>{active=false;clearInterval(timer);};},[]);
  const runAction=async(id:ActionId)=>{setConfirming(null);setActionError('');try{const response=await fetch(`/api/actions/${id}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'}});const data=await response.json() as ActionJob&{error?:string};if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);setJob(data);}catch(caught){setActionError(caught instanceof Error?caught.message:'Action failed');}};
  const previewConfig=async()=>{if(!draft)return;setConfigMessage('');try{const response=await fetch('/api/config/preview',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const data=await response.json() as ConfigPreview&{error?:string};if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);if(!data.changes.length){setConfigMessage('Nothing changed.');return;}setPreview(data);}catch(caught){setConfigMessage(caught instanceof Error?caught.message:'Preview failed.');}};
  const applyConfig=async()=>{if(!preview)return;try{const response=await fetch('/api/config/apply',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:preview.token})});const data=await response.json() as{message?:string;error?:string};if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);setPreview(null);await loadConfig();setConfigMessage(data.message||'Settings saved.');}catch(caught){setPreview(null);setConfigMessage(caught instanceof Error?caught.message:'Save failed.');}};
  const setNumber=(group:'rates'|'progression'|'wild',key:string,value:number)=>draft&&setDraft({...draft,[group]:{...draft[group],[key]:value}}); const setImportant=(key:keyof Draft['important'],value:Draft['important'][keyof Draft['important']])=>draft&&setDraft({...draft,important:{...draft.important,[key]:value}});
  const addMod=()=>{if(!draft)return;const id=newMod.trim();if(!/^\d+$/.test(id)){setConfigMessage('Enter a numeric CurseForge Project ID.');return;}if(draft.mods.includes(id)){setConfigMessage('That mod is already listed.');return;}setDraft({...draft,mods:[...draft.mods,id]});setNewMod('');};
  const moveMod=(index:number,direction:-1|1)=>{if(!draft)return;const target=index+direction;if(target<0||target>=draft.mods.length)return;const mods=[...draft.mods];[mods[index],mods[target]]=[mods[target],mods[index]];setDraft({...draft,mods});};
  const addAdmin=()=>{if(!draft)return;const id=newAdmin.trim();if(!/^[A-Za-z0-9]{32}$/.test(id)){setConfigMessage('Enter the full 32-character EOS/OSS Account ID from whoami.');return;}if(draft.admins.includes(id)){setConfigMessage('That account is already an admin.');return;}setDraft({...draft,admins:[...draft.admins,id]});setNewAdmin('');};
  const backupText=useMemo(()=>!status?.backup.found||!status.backup.timestamp?'Not found':new Intl.DateTimeFormat('en',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(status.backup.timestamp)),[status]);
  const cards=[{label:'Server',value:status?(status.server.running?'Online':'Stopped'):'Checking…',detail:status?.server.running?`PID ${status.server.pid} · ${status.server.privateMemoryGb} GB`:(error||'Windows host'),tone:status?.server.running?'green':'cyan'},{label:'Map',value:status?.server.map||'Aberration',detail:status?.server.mapId||'Aberration_WP',tone:'violet'},{label:'Capacity',value:status?.server.maxPlayers?`0 / ${status.server.maxPlayers}`:'—',detail:status?`${status.server.modCount} cross-platform mods`:'Waiting',tone:'amber'},{label:'Last backup',value:status?backupText:'Checking…',detail:'Verified snapshot',tone:'green'}];
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="brandMark">A</span><div><p className="eyebrow">Gustav&apos;s private server</p><h1>ASA Control Deck</h1></div></div><div className={`connectionBadge ${error?'offline':''}`}><span/>{error||'Local service connected'}</div></header>
    <section className="hero"><div><p className="eyebrow">ARK: Survival Ascended</p><h2>Your complete LAN manager.</h2><p className="heroCopy">Guarded operations, rates, progression, mods, admins, wild dinos, and important settings. No Codex credits required to use it.</p></div><div className="modeCard"><span className="modeIcon">◉</span><div><strong>Preview + backup protected</strong><small>Config applies only while ASA is stopped</small></div></div></section>
    <section className="stats">{cards.map((card)=><article className={`statCard ${card.tone}`} key={card.label}><p>{card.label}</p><strong>{card.value}</strong><small>{card.detail}</small></article>)}</section>
    <div className="contentGrid"><section className="panel actionsPanel"><div className="sectionHeading"><div><p className="eyebrow">Operations</p><h3>Server controls</h3></div><span className={`locked ${job.state}`}>{job.state==='running'?'Working…':'Protected'}</span></div><div className="actionGrid">{actions.map((action)=><button key={action.id} disabled={job.state==='running'} onClick={()=>setConfirming(action.id)}><span>{action.icon}</span><b>{action.label}</b><small>{action.detail}</small></button>)}</div><p className={`panelNote actionResult ${job.state}`}>{actionError||job.message||'Every disruptive action asks for confirmation.'}</p></section>
    <section className="panel healthPanel"><div className="sectionHeading"><div><p className="eyebrow">Host health</p><h3>Windows server PC</h3></div></div>{[['Memory',status?`${status.host.memoryUsedGb} / ${status.host.memoryTotalGb} GB`:'Waiting…',status?.host.memoryPercent||0],['CPU',status?`${status.host.cpuPercent}%`:'Waiting…',status?.host.cpuPercent||0],['Disk free',status?`${status.host.diskFreeGb} GB`:'Waiting…',status?65:0]].map(([label,value,width])=><div className="meter" key={String(label)}><div><span>{label}</span><b>{value}</b></div><i><em style={{width:`${width}%`}}/></i></div>)}<div className="safetyRow"><span>✓</span><p><b>Local and independent</b><small>Works without AI services</small></p></div></section></div>
    {config&&draft&&<>
      <section className="panel managerSettings"><div className="sectionHeading"><div><p className="eyebrow">Gameplay</p><h3>Guided server rates</h3></div><button className="saveConfigButton" onClick={previewConfig}>Preview all changes</button></div><p className="sectionIntro">Higher is faster or more unless the description says lower.</p><NumberGrid definitions={config.rateDefinitions} values={draft.rates} onChange={(key,value)=>setNumber('rates',key,value)}/></section>
      <section className="panel managerSettings"><div className="sectionHeading"><div><p className="eyebrow">Characters + world</p><h3>Progression and time</h3></div></div><label className="toggleRow"><input type="checkbox" checked={draft.allowSpeedLeveling} onChange={(event)=>setDraft({...draft,allowSpeedLeveling:event.target.checked})}/><span><b>Allow native movement-speed leveling</b><small>Players and non-flyers; native ASA has no hard speed cap.</small></span></label><NumberGrid definitions={config.progressionDefinitions} values={draft.progression} onChange={(key,value)=>setNumber('progression',key,value)}/></section>
      <section className="panel managerSettings"><div className="sectionHeading"><div><p className="eyebrow">Spawns + loot</p><h3>Wild dinos</h3></div></div><label className="selectRow"><span><b>Level distribution</b><small>Requires Custom Dino Levels mod 928708.</small></span><select value={draft.levelDistribution} onChange={(event)=>setDraft({...draft,levelDistribution:event.target.value as Draft['levelDistribution']})}><option value="equal">Equal levels</option><option value="high">Skew high</option><option value="rag">Ragnarok style</option></select></label><NumberGrid definitions={config.wildDefinitions} values={draft.wild} onChange={(key,value)=>setNumber('wild',key,value)}/><p className="panelNote">After restart, use Reset wild dinos for population, difficulty, or distribution changes.</p></section>
      <section className="panel managerSettings"><div className="sectionHeading"><div><p className="eyebrow">Private server</p><h3>Important settings</h3></div></div><div className="toggleGrid">{[['serverPVE','PvE mode'],['allowFlyerCarryPvE','Allow flyers to carry wild creatures in PvE'],['alwaysAllowStructurePickup','Always allow structure pickup'],['noRespawnPenalty','Disable escalating repeated-death respawn penalty']].map(([key,label])=><label className="toggleRow" key={key}><input type="checkbox" checked={Boolean(draft.important[key as keyof Draft['important']])} onChange={(event)=>setImportant(key as keyof Draft['important'],event.target.checked)}/><span><b>{label}</b></span></label>)}</div><div className="compactGrid">{[['autosaveMinutes','Autosave minutes',5,60],['maxTamedDinos','Global tame cap',100,5000],['simpleBedCooldown','CS Simple Bed cooldown (seconds)',0,600],['modernBedCooldown','CS Bunk Bed cooldown (seconds)',0,600]].map(([key,label,min,max])=><label className="compactField" key={String(key)}><span>{label}</span><input type="number" min={Number(min)} max={Number(max)} value={Number(draft.important[key as keyof Draft['important']])} onChange={(event)=>setImportant(key as keyof Draft['important'],Number(event.target.value))}/></label>)}</div><div className="passwordGrid"><label><span>Join password <small>{config.important.joinPasswordConfigured?'currently configured':'currently blank'}</small></span><input type="password" placeholder="Blank keeps current" value={draft.important.joinPassword.value} onChange={(event)=>setImportant('joinPassword',{mode:event.target.value?'replace':'keep',value:event.target.value})}/><button onClick={()=>setImportant('joinPassword',{mode:'clear',value:''})}>Clear join password</button></label><label><span>Admin password <small>{config.important.adminPasswordConfigured?'currently configured':'missing'}</small></span><input type="password" placeholder="Blank keeps current" value={draft.important.adminPassword.value} onChange={(event)=>setImportant('adminPassword',{mode:event.target.value?'replace':'keep',value:event.target.value})}/></label></div></section>
      <section className="panel modsPanel"><div className="sectionHeading"><div><p className="eyebrow">Cross-platform</p><h3>Mod order</h3></div><span className="modCount">{draft.mods.length} mods</span></div><div className="addModRow"><input inputMode="numeric" placeholder="CurseForge Project ID" value={newMod} onChange={(event)=>setNewMod(event.target.value)} onKeyDown={(event)=>event.key==='Enter'&&addMod()}/><button onClick={addMod}>Add mod</button></div><ol className="modList">{draft.mods.map((id,index)=><li key={id}><span>{index+1}</span><code>{id}</code><div><button onClick={()=>moveMod(index,-1)} disabled={index===0}>↑</button><button onClick={()=>moveMod(index,1)} disabled={index===draft.mods.length-1}>↓</button><button className="removeMod" onClick={()=>setDraft({...draft,mods:draft.mods.filter((item)=>item!==id)})}>Remove</button></div></li>)}</ol></section>
      <section className="panel modsPanel"><div className="sectionHeading"><div><p className="eyebrow">PS5 + EOS</p><h3>Permanent admins</h3></div><span className="modCount">{draft.admins.length} admins</span></div><p className="sectionIntro">Run <code>whoami</code> in the PS5 console and use the full 32-character Account ID—not the PSN name.</p><div className="addModRow"><input maxLength={32} placeholder="32-character EOS/OSS Account ID" value={newAdmin} onChange={(event)=>setNewAdmin(event.target.value)} onKeyDown={(event)=>event.key==='Enter'&&addAdmin()}/><button onClick={addAdmin}>Add admin</button></div><ol className="modList">{draft.admins.map((id,index)=><li key={id}><span>{index+1}</span><code>{id}</code><div><button className="removeMod" onClick={()=>setDraft({...draft,admins:draft.admins.filter((item)=>item!==id)})}>Remove</button></div></li>)}</ol></section>
      <section className="panel managerSettings"><div className="sectionHeading"><div><p className="eyebrow">Quick guide</p><h3>Server files</h3></div></div><div className="fileGrid">{config.files.map((file)=><article key={file.name}><b>{file.name}</b><p>{file.detail}</p><small>{file.safety}</small><code>{file.path}</code></article>)}</div></section>
      <section className="saveBar"><div><b>Review everything before writing</b><span>{configMessage||'Preview compares every section. Apply is blocked while ASA is running.'}</span></div><button onClick={previewConfig}>Preview all changes</button></section>
    </>}
    {confirming&&<div className="modalBackdrop" onClick={()=>setConfirming(null)}><div className="confirmModal" onClick={(event)=>event.stopPropagation()}><p className="eyebrow">Confirm server action</p><h3>{actions.find((item)=>item.id===confirming)?.label}</h3><p>{actions.find((item)=>item.id===confirming)?.warning}</p><div><button className="cancelButton" onClick={()=>setConfirming(null)}>Cancel</button><button className="confirmButton" onClick={()=>runAction(confirming)}>Confirm</button></div></div></div>}
    {preview&&<div className="modalBackdrop" onClick={()=>setPreview(null)}><div className="confirmModal previewModal" onClick={(event)=>event.stopPropagation()}><p className="eyebrow">Preview → confirm → backup → apply</p><h3>Review {preview.changes.length} change(s)</h3><p>ASA must be safely stopped before apply. A timestamped config snapshot is created first.</p><ul>{preview.changes.map((change,index)=><li key={`${change.group}-${change.key}-${index}`}><code>{change.group}: {change.key}</code><span>{String(change.from)} → {String(change.to)}</span></li>)}</ul><div><button className="cancelButton" onClick={()=>setPreview(null)}>Cancel</button><button className="confirmButton" onClick={applyConfig}>Backup + apply</button></div></div></div>}
    <footer><span>ASA Control Deck · complete LAN manager</span><span>Original manager preserved</span></footer>
  </main>;
}
